name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Build and Push Docker image to Artifact Registry
      run: |
        IMAGE="southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dpbaby/app"
        gcloud auth configure-docker southamerica-east1-docker.pkg.dev
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        IMAGE="southamerica-east1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/dpbaby/app"
        gcloud run deploy ${{ secrets.GCP_SERVICE }} \
          --image $IMAGE \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
